### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ashutosh1982** [chrisz/pyhusmow#1]
I could not find any other way of contacting the author, so I am posting my message as an issue. I am interested to know how did the author determine the API for the automower? Is there any documentation that is available from Husqvarna ? Is there any way we can officially get the API from Husqvarna, instead of using something that can stop working or change anytime? Please contact me at jaiswal.ashutosh@gmail.com

**Comment by chrisz** [comment]
Hi,

I found no documentation about API to control automowers. I don't think there is a a public API.

To find URLs to control the automower, I unpacked the Automower Connect app for Android.

If you find an official way to control the robot without using the Automower Connect app, I'm interested in.

**Comment by whiteadam** [comment]
I would also be interested :-)
