### ISSUE TITLE
Petition for militating to have an official API ...

### ISSUE THREAD

**Issue by ghost** [chrisz/pyhusmow#10]
Petition for militating to have an official API ...

https://www.change.org/p/husqvarna-open-an-api-for-automover-husqvarana/

**Comment by CaselIT** [comment]
Nice idea, I've signed it!

**Comment by rannmann** [comment]
"Automover"

**Comment by mr2web** [comment]
Signed it. But isn't it possible to change the titel to Automower instead of Automover?

**Comment by ghost** [comment]
It's done.
Best Regards
Thomas
