### ISSUE TITLE
PHP Class

### ISSUE THREAD

**Issue by ghost** [chrisz/pyhusmow#15]
Hi,

Sorry for my english. I have translate your job in a php class.
I can publish it on a different repository or on yours.
What do you prefere ?

Best regards
Thomas

**Comment by chrisz** [comment]
Hi,

Sorry for the delay. You can publish your php class in your own repository. If you want, you can add a comment in your class with a link to my repo (but not an obligation at all).

Chris

**Comment by ghost** [comment]
Hi,

I have done my own repository : https://github.com/guenneguezt/phphusqvarna

Thomas
