### ISSUE TITLE
this code no longer works due to the site certificate expiration

### ISSUE THREAD

**Issue by deepbrain** [chrisz/pyhusmow#18]
https://iam-api.dss.husqvarnagroup.net/

SSL Certificate:

Issued On	Thursday, February 23, 2017 at 4:00:00 PM
Expires On	Saturday, March 24, 2018 at 5:00:00 AM

**Comment by CaselIT** [comment]
Seems to be ok now

**Comment by fafoulon** [comment]
They renewed the certificate the same day, it was also blocking the iPhone app.

**Comment by chrisz** [comment]
If it's ok now, I close this issue.
