### ISSUE TITLE
How frequent do you pull?

### ISSUE THREAD

**Issue by tnemrap** [chrisz/pyhusmow#23]
How frequent do Husqvarna accept that we pull status?

**Comment by simlu** [comment]
We've been pulling every minute for a month now and that seems to be no problem. How often are you planning to pull and with what purpose?

**Comment by tnemrap** [comment]
Every minute is ok for me. I want to have right status in OpneHAB.

**Comment by simlu** [comment]
Great!

Also for future reference note that the status is only updated every 30 seconds (for the model we checked). So querying more often doesn't make sense. However we have not tested if a sub 60 second request rate would get one rate limited.

Please close this ticket if your question is answered!

**Comment by jonasdig** [comment]
Does pulling interval have any impact on the power consumption for the mower?

**Comment by simlu** [comment]
I would be very surprised if it did
