### ISSUE TITLE
401 Client Error: Unauthorized for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers

### ISSUE THREAD

**Issue by dominikraff** [chrisz/pyhusmow#34]
On my UbuntuServer, i get this error now after starting my server:
husmow --login yourmaillogin --password yourpassword server --address 0.0.0.0 --port 2345

`Logger configured
Try to execute /status
401 Client Error: Unauthorized for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers
[ERROR] Retrying to send the command 2
Done
401 Client Error: Unauthorized for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers
[ERROR] Retrying to send the command 1
Done
[ERROR] Failed to send the command
<IPDARESS>- - [17/Apr/2020 07:08:05] "GET /status HTTP/1.1" 500 -
Done`

**Comment by chrisz** [comment]
Hello, sorry but I have no more time to maintain this repository. Husqvarna provides an official api now, you can easily use it: https://developer.1689.cloud/apis/Automower+Connect+API .
