### ISSUE TITLE
Python returning AttributeError

### ISSUE THREAD

**Issue by iotnl** [chrisz/pyhusmow#4]
Hi, whilst running your awesome script on Raspbian Python3, I get...

_Traceback (most recent call last):
  File "husmow.py", line 335, in <module>
    config = create_config(args)
  File "husmow.py", line 186, in create_config
    if args.expire_status:
AttributeError: 'Namespace' object has no attribute 'expire_status'_

...and script exits. Basically irrespective of command line contents. Did I overlook anything?

Thanks!

**Comment by chrisz** [comment]
I just fix this problem. Thanks for reporting it :-).
