### ISSUE TITLE
Correct use of --save command line option

### ISSUE THREAD

**Issue by iotnl** [chrisz/pyhusmow#5]
Note on https://github.com/chrisz/pyhusmow/blob/master/README.md..
The _'Save configuration in configuration file'_ section currently reads:

"To save information, just type your command with all information and add the option --save to command line:

_python husmow.py --login yourmaillogin --password yourpassword --log-level INFO control PARK_

And the next time you run the command, you can omit these information from the command line:

_python husmow.py control PARK_"

I assume you meant to write '--save' in the top command line instead of 'INFO'? Otherwise the config wouldn't be saved ;-).

**Comment by chrisz** [comment]
You are right :-). I just fix the doc. Thanks.
