### ISSUE TITLE
Option for selecting language?

### ISSUE THREAD

**Issue by magnushacker** [chrisz/pyhusmow#6]
After I downloaded and started using the script, I noticed that the AM Connect app started giving me notifications (e.g when the mower is switched on or off) in French. The reason is that the <language> parameter is sent with the value "fr-FR" by the script, which I guess is cached somewhere by the Husqvarna servers. After I changed it to "en-US", my notifications are now in English again.

Maybe a good idea to make the language an option?

**Comment by chrisz** [comment]
Hi,

Thanks for reporting this problem. I will fix it the next time I work on pyhusmow.

**Comment by CaselIT** [comment]
This issue should no longer be relevant given the updated api

**Comment by chrisz** [comment]
Thanks @CaselIT , I close this issue :-)
