### ISSUE TITLE
Explanation of installation steps

### ISSUE THREAD

**Issue by bartbutenaers** [chrisz/pyhusmow#8]
Hey Christophe,

Thanks for sharing your project with us!  

Would it be possible to update the readme.md file with some explanation about the hardware and wiring you have used?  Or perhaps some links to site(s) where we can find the steps to accomplish this.

Thanks again !
Bart Butenaers

**Comment by chrisz** [comment]
Hi,

There is no special hardware to run pyhusmow. You can install pyhusmow on a simple computer but you need the GPS/GSM module to control your automower remotely.

Chris

**Comment by richardpub4136** [comment]
A when the cutting setting ???
We are already too happy with this super script that now turns on the rapsberry.
With an interface on Ipad realized by philippe in Lifedomus

![image](https://cloud.githubusercontent.com/assets/28557864/26284693/b0c77b4e-3e41-11e7-8c5a-18a732469fcb.png)

**Comment by chrisz** [comment]
Not enough time to work on cutting settings now and I don't think theses settings change often.

**Comment by richardpub4136** [comment]
Ok I understand...
I'm looking for myself...
